name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: read

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          registry-url: 'https://npm.pkg.github.com'
          scope: '@la-jarre-a-son'

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: npm run package

      - name: Check Lint
        run: npm run lint

      - name: Check Types
        run: npm exec tsc

      - name: Check Unit Tests
        run: npm test
